baseURL: "https://github.com/chenyuan9/magisk_hugo.info"
RelativeURLs: true
CannonifyURLs: true
languageCode: en
title: Magisk_xzy
theme: hugo-theme-ava
paginate: 7
mainSections: post
languages:
  en:
    canonifyURLs: yes
    enableEmoji: yes
    enableRobotsTXT: yes
    languageName: English
module:
  hugoVersion:
    extended: yes
    min: 0.87.0
params:
  disqus: xxxxxxx
  ga_id: ''
  mainSections: post
  meta_tags:
    meta_description: Ava is a light theme for your blog with essential features you
      might dig in.
    meta_og_description: Ava is a light theme for your blog with essential features
      you might dig in.
    meta_og_image: https://raw.githubusercontent.com/jmau111/hugo-theme-ava/main/images/default.jpeg
    meta_og_sitename: Hugo Ava Theme
    meta_og_title: Hugo Ava Theme
    meta_og_type: website
    meta_og_url: https://hugo-ava.netlify.app
    meta_twitter_card: summary
    meta_twitter_creator: '@gohugoio'
    meta_twitter_site: '@gohugoio'
markup:
  blackFriday:
    angledQuotes: yes
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: yes
    guessSyntax: yes
    lineNos: no
    noClasses: no
    pygmentsCodefences: yes
    pygmentsUseClasses: yes
    tabWidth: 4
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: Archives
      url: /posts/
      weight: 3
permalinks:
  pages: /:filename/
  posts: /:year/:month/:day/:slug/
